sudo: false
language: scala
scala:
- 2.12.7
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test
jdk:
- oraclejdk8
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
before_install:
- if [ $TRAVIS_PULL_REQUEST = "false" ]; then openssl aes-256-cbc -K $encrypted_1dd79adeb524_key
  -iv $encrypted_1dd79adeb524_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar
  -d; tar xv -C travis -f travis/local.secrets.tar; fi
