sudo: false
language: scala
scala:
- 2.12.7
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test
jdk:
- oraclejdk8
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
env:
  global:
  - secure: GXs/Ll93Uz4afWrQX8uUWa2ggd/pIpMFXVQIGVAdeAy80n2xorM/6dD1FHGR0VK2weavomLmmQfAG5DXIepNm9QVZIBsxu09VuI+3I1rh17JQiDUmsLJilQ9RQ1xPzOMPbxizaV0TVX/OsapRVTJCnQjckHXLUIH2BxxChkdAoqZJvIvrUmoXqeIHaCeaj3pbSF3PttNcApNri7UhfTO/eZ+AFzcaWFym5Nuv2Uhf3NLT16zP4wbhBhb8ByV6kmiA1ciemeGHhBMBu51C4W+3gxeVhOC6FjFeeYfXPd8l2YaKZ+CNLg5a8zKuy+uUhVAQnccmwdG7djObsBuns/yCGLVnxmEFZaRbk7lMF6ZmWi7JIP0fo4cHUZY63AmZfjmbCEAQo5kJ+3tfc33b/Ba67JDTls3dJPyT/dHe0NNG6vjeXJbCEIdyjH2LmzJCbGs0jiYUJwdFG6hV+HqcXKhz7WcRrb26eZbb3cPGuexm6xBLTleV3x71uKH3aX072Uwwv8ABXgmMFKMsmqmU3vz2RK3Ngb0hkOsxOYDZdNEqI0NruTzVl2pl0LibVOXft9Sk6Lc9RrBn2jQ7Upm0CMSoeQxDVs3ELXHR8xX7w+hEZgWdNWkhnE2mY8zMrbqS07dIWGLtAM2UgLTpyoKRONz179Pb7UZexMZ6Q9L01eQl8A=
  - secure: yROTotRwMJnXIkyT6UWApp51A2f7qbMi/yrHtojHeNduw/EuOELU+J2L94xue4KeK1EsSFp1BpmcwePBWQea3p4Jrq/ziCg9yhfMZErqF7PZBfJCFnTzbqqDp1OdldNL3uV9rIYOyt8f/lB18XP9EpynGpa2JJR0m+UywX+DbCb2L2zEyZ6cSBhNhJ1OW1SP4XBOMcR0goJhoo8rnIEFgPThnuislJfA6Mqa9CsZTIWGdViP+L4JPmYrMo0TtQBg5ANyBrbxuhXAFr9+kf/xGor1eFhbdcF6ucEeBnaCaErU+C/mp9lb9HlUriEwRqFAXkZ3bjHRAsggBZ/c1/Df2nuXumOIvH9xyVcnQr6A90d3AoW6WN82S8kf6HRID01LGCjWxuDnZ5AaYXdQuACG0QMI9cvN+cH+1d1DKOw9DKZOyvGneuU1Do/0n8Phz50rw4RlN1/jJXW8TpCo1/443VQWftFp3HJ7YLvSMLrRoZmr0hNMBgLn5K98nWLm+Vjv2PNe3upjiHrsGTsLa0KrcQwRNqWUrvETFID4OXeJCrTAHrn1BkWnv9DvAvy5IbxZ9bnEryCu+Ld2wbF4mmYGBKowI8Ii9z6JX1Gluz8Y1PxVRH7dUdiOZ9Xa+bnrICT6Q0bVJv8EiBTdf0sSBHIdd+/Q+e/aSKTDQnT0/HBQ+pk=
  - secure: YY+o4UVEMhZ/IWLfH7NrYQ/XKkFqYZ2pticaa/wBpZMK0ouqUDkcfMhLDiHjCzniMDgm4mPhL0tC3JToNbCn29lrpsQXZo7ToTiLPqnBtwiitLdvfvMRkBNjNjVLV8KaHx92PkEoYRLZJojIYyham0mh9uMlLUBrWr2NiIXpUWJGgLZWw8exyx29gHgSn6jhwFyeeo+oE2Ep6PmwxRbK7XhU78G81ZMIxVb9ipXRmHL1W3Qv/Jx2itj6ZYBviiW38H1ffoHTJfyIbn2JzWUS6Kk2eXE9ps7Au+OABuzcEWPsFgAMg83YGivDHaONKO1At4c1L2J/XBqDm8cmi2+GCoK8arRnpV2+sDiBS2bAUlDEOIuK05tOr2Wzr0KmEeg1UXyxulyXz8msNxG6yWN8UTc13FbW1rAmSTgqitUo/RwZo/1RZz9GbJJqQ+MhnZzIAu3Exl8pvQUIIS+mtUDFMcGD3DFVk413vTlUFRsTvTMb9cnFb/8morZOKFMCXb7UCLZJPaWDgWRCWITo9OzM+jg12fVPSv+k02z8w+YBTrcgH3tqw0dkNWJ/gZYndmFYnPqHqm/uiiBErC55EGaM1+NkZp+58nfvzLA/C0yudU+CwsrpmATKRG7F4jqKWYvlsyTyjhk0nMOeiDkEojYlzE6re3HNAP+R5RPZ9avDrdQ=
before_install:
  - if [ $TRAVIS_PULL_REQUEST = "false" ]; then
    openssl aes-256-cbc -K $encrypted_1dd79adeb524_key -iv $encrypted_1dd79adeb524_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
    fi
